engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
exclude_paths:
  - software/owh/client/node_modules/**/*
  - software/owh/client/bower_components/**/*
  - software/owh/client/.bowerrc
  - software/owh/client/.gitignore
  - software/owh/client/.jshintrc
  - software/owh/client/bower.json
  - software/owh/client/package.json
  - software/owh/client/vendor/**/*
  - software/owh/client/test/*
  - software/owh/server/node_modules/**/*
  - software/owh/server/.gitignore
  - software/owh/server/package.json
  - software/owh/server/test/*
  - software/owh/server/uploads/*
