# Default config
default: 
  elastic_search:
    url: 'http://localhost:9200/'
  rserve:
    host : localhost
    port : 6311
    user : ''
    password : ''
  yrbs:
    queryUrl: ''
    questionsUrl: ''
  logging:
    level: 'debug'
  fb:
    appID :
    appURL:

# Dev configuration
dev:

# Test environment configuration
test:

# Production configuration
production:
  elastic_search:
    url:
  rserve:
    host:
      user:
      password:
  fb:
    appID :
    appURL:
