# Default config
default: 
  elastic_search:
    url: 'http://localhost:9200/'
  rserve:
    host : localhost
    port : 6311
    user : ''
    password : ''
  logging:
    level: 'debug'
  fb:
    appID : 11600523216727
    appURL: 'http://owh.semanticbits.com/'

# Dev configuration
dev:
    
# Test environment configuration    
test:
 
# Production configuration    
production: 
  elastic_search:
    url: 
  rserve:
    host:
      user:
      password:
  fb:
    appID :
    appURL:
