data_file:
  # when local_directory is set the data files will processed from this local directory and AWS properties will be ignored
  local_directory: '/home/ashok/projects/OWH/natality/data_files'
  # AWS S3 bucket information, when local_directory peroperty is not specified above, the ETL will try to download the data files
  # from the directory in the AWS S3 bucket specified below
  aws_access_key_id: 'aws access key'
  aws_secret_access_key: 'aws secret key'
  aws_s3_bucket_name: 'owh-data'
  aws_s3_directory: 'datasets/census'
elastic_search:
  host: 127.0.0.1
  port: 9200
  bulk_load_size: 10000
  index: owh_census_rates
  type: census_rates
  type_mapping: census-rates-type-mapping.json
